### ISSUE TITLE
Aspects over async iterators fail to compile in projects targeting net8.0 or net9.0

### ISSUE THREAD

**Issue by gfraiteur** [metalama/Metalama#1963]
## Summary

In 2027.0, an aspect that overrides an async iterator fails to compile when the target project targets `net8.0` or `net9.0`. The error is:

```
error LAMA0611: Error CS0117 in code generated by aspect '<AspectName>':
'RunTimeAspectHelper' does not contain a definition for 'BufferAsync'
error LAMA0612: The most likely cause of the compilation failure is a bug in an aspect.
```

The same code compiles under 2026.1.

## Cause

Commit 575be8b88a, "Replace the net8.0 target framework by net10.0 (#1876)", changed the target frameworks of `Metalama.Framework.Redist` from `netstandard2.0;net8.0` to `netstandard2.0;net10.0`.

A project targeting `net8.0` or `net9.0` cannot consume the `net10.0` asset, so NuGet now resolves the `netstandard2.0` asset. That asset does not contain `RunTimeAspectHelper.BufferAsync`, `AsyncEnumerableList<T>`, `AsyncEnumerableArray<T>` or `RunTimeAspectHelper.AsyncEnumerator<T>`, because those members are declared inside `#if NET5_0_OR_GREATER` in `Metalama.Framework/src/Metalama.Framework/RunTime/RunTimeAspectHelper.cs`.

When a template calls `meta.Proceed()` on a method whose iterator kind is `IAsyncEnumerable` or `IAsyncEnumerator`, `ProceedHelper.GenerateAwaitBufferAsync` emits `await RunTimeAspectHelper.BufferAsync( ... )` unconditionally. There is no fallback path for a target framework where the method is absent, so the generated code does not compile.

## Impact

Any user project targeting `net8.0` or `net9.0` that applies an aspect over an `async IAsyncEnumerable<T>` or `async IAsyncEnumerator<T>` method fails to build. The .NET 10 SDK still builds `net8.0` and `net9.0` projects, so the regression is not visible until an async iterator is involved.

The aspect test suite does not detect this, because the test projects were retargeted to `net10.0` in the same commit.

Affected versions: 2027.0. Not affected: 2026.1 and earlier, where `Metalama.Framework.Redist` still ships a `net8.0` asset.

## Reproduction

The `Metalama.Tests.NopCommerce` build fails on `dev/2027.0`. All projects in that repository target `net8.0`.

Build: https://postsharp.teamcity.com/buildConfiguration/Metalama_Metalama20270_MetalamaTests_MetalamaTestsNopCommerce_DebugBuild/334590

Six errors are reported in `src/Libraries/Nop.Services/Attributes/AttributeParser.cs`, at the two `async IAsyncEnumerable` members `GetValuesAsync` and `ParseAttributeValues`, from the aspects `UninlineableOverrideAspect` and `ForcedJumpOverrideAspect`.

## Possible resolutions

1. Add a downlevel runtime asset back to `Metalama.Framework.Redist`, for example `net8.0`, so that projects targeting `net8.0` and `net9.0` keep the async iterator members.
2. Compile the async iterator members for `netstandard2.0` as well, by referencing `Microsoft.Bcl.AsyncInterfaces` and relaxing the `NET5_0_OR_GREATER` conditions. The package already references `Microsoft.Bcl.HashCode` under a `netstandard2.0` condition.
3. Decide that 2027.0 no longer supports aspects over async iterators in projects targeting `net8.0` or `net9.0`. In that case, `ProceedHelper` should report a clear diagnostic instead of emitting code that does not compile, and the change should be documented as a breaking change.

Whichever resolution is chosen, an aspect test that targets a downlevel framework would prevent the regression from recurring.

— Claude for Gael Fraiteur
